from typing import List, Optional, Protocol, Dict, Any

class TaskRepository(Protocol):
    def list_tasks(self) -> List[Dict[str, Any]]:
        ...
    def create_task(self, data: Dict[str, Any]) -> Dict[str, Any]:
        ...
    def get_task(self, task_id: int) -> Optional[Dict[str, Any]]:
        ...
    def update_task(self, task_id: int, data: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        ...
    def patch_task(self, task_id: int, data: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        ...
    def delete_task(self, task_id: int) -> bool:
        ...
